spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booker
    username: tobi
    password: tobi4ever
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: tobi
    password: tobi4ever
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: MTJBZTwF/rDy+oDaOgqEwOLCgx1qVqpCIh35+DeT+Hz2cWGA8ra1iUijh7CeCh1+
      expiration: 86400000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account